GET http://localhost:3000/expedientes/

###

GET http://localhost:3000/expedientes?demandado=ANSES


###

GET http://localhost:3000/expedientes?idfuero=CNT


###

GET http://localhost:3000/expedientes?idfuero=CSS&juzgado=5


###

GET http://localhost:3000/expedientes/CIV0194832020
